spring:
  application:
    name: SpringGateway

  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: false
    show-sql: false
    format-sql: true
    hibernate:
      ddl-auto: create
  # [스프링 부트 메시지 관련 설정]
  messages:
    basename: message/messages
    encoding: UTF-8

  data:
    redis:
      host: localhost      # 또는 Redis 서버 주소
      port: 6379           # 기본 Redis 포트

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/test_realm
          jwk-set-uri: http://localhost:8088/realms/test_realm/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: ms1
          uri: lb://MS1
          predicates:
            - Path=/ms1/**
        - id: ms2
          uri: lb://MS2
          predicates:
            - Path=/ms2/**
        - id: userService
          uri: lb://USERSERVICE
          predicates:
            - Path=/user/**


jwt:
  secretKey: WQJEQIEQWIEJQWID21312JMDKWQI99381DJWI1930D
  access:
    header: Authorization
  refresh:
    header: Authorization-refresh

keycloak:
  server:
    url: http://localhost:8088
    realm: test_realm
    client-id: test_portal

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.springframework.cloud.gateway: DEBUG
    p6spy: DEBUG
    p6spy.spy: OFF

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka